--------------------------------------------------------
--  File created - Monday-October-05-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table M_ADMIN
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_ADMIN" 
   (	"ID" NUMBER, 
	"FIRSTNAME" VARCHAR2(100 BYTE), 
	"LASTNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"TYPE" VARCHAR2(100 BYTE), 
	"PROFILE_PICTURE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_CART
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_CART" 
   (	"ID" NUMBER, 
	"ADMIN_ID" NUMBER, 
	"SHOWTIME_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"TICKET_ID" NUMBER, 
	"TOTAL_PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_HALL
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_HALL" 
   (	"ID" NUMBER, 
	"THEATRE_ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"MAX_CAPACITY" NUMBER, 
	"AVAILABILITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_MOVIES
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_MOVIES" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(60 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"TRAILERS" VARCHAR2(1000 BYTE), 
	"AVAILABILITY" NUMBER, 
	"COVER_PICTURE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_REVIEWS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_REVIEWS" 
   (	"ID" NUMBER, 
	"MOVIE_ID" NUMBER, 
	"ADMIN_ID" NUMBER, 
	"RATINGSCALE" NUMBER, 
	"REVIEW" VARCHAR2(1000 BYTE), 
	"R_DATE" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_SHOWTIME
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_SHOWTIME" 
   (	"ID" NUMBER, 
	"MOVIE_ID" NUMBER, 
	"M_DATE" VARCHAR2(80 BYTE), 
	"TIME_FROM" VARCHAR2(80 BYTE), 
	"TIME_TO" VARCHAR2(80 BYTE), 
	"HALL_ID" NUMBER, 
	"STATUS" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_THEATRE
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_THEATRE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(80 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STATE" VARCHAR2(10 BYTE), 
	"ZIPCODE" VARCHAR2(20 BYTE), 
	"PHONENUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_TICKETS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_TICKETS" 
   (	"ID" NUMBER, 
	"MOVIE_ID" NUMBER, 
	"PRICE" NUMBER(10,2), 
	"DATE_FROM" VARCHAR2(80 BYTE), 
	"DATE_TO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table M_USERTICKETS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."M_USERTICKETS" 
   (	"ID" NUMBER, 
	"ADMINE_ID" NUMBER, 
	"SHOWTIME_ID" NUMBER, 
	"TICKET_ID" NUMBER, 
	"RESERVE_DATE" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.M_ADMIN
SET DEFINE OFF;
Insert into TESTDB.M_ADMIN (ID,FIRSTNAME,LASTNAME,EMAIL,PASSWORD,TYPE,PROFILE_PICTURE) values (1,'Ahmed','Hameed','a@h.com','80012','User',null);
Insert into TESTDB.M_ADMIN (ID,FIRSTNAME,LASTNAME,EMAIL,PASSWORD,TYPE,PROFILE_PICTURE) values (2,'Majeed','AlDamah','m@d.com','80012','Administrator',null);
REM INSERTING into TESTDB.M_CART
SET DEFINE OFF;
Insert into TESTDB.M_CART (ID,ADMIN_ID,SHOWTIME_ID,QUANTITY,TICKET_ID,TOTAL_PRICE) values (6,1,4,4,1,7);
REM INSERTING into TESTDB.M_HALL
SET DEFINE OFF;
Insert into TESTDB.M_HALL (ID,THEATRE_ID,NAME,TYPE,MAX_CAPACITY,AVAILABILITY) values (1,1,'C-9','2D',100,1);
REM INSERTING into TESTDB.M_MOVIES
SET DEFINE OFF;
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (1,'Furious 7','Furious 7 movie','https://www.youtube.com/embed/_Ey7ysLYbIo?autoplay=0',1,'http://www.filmxy.com/wp-content/uploads/2015/04/Furious-7-2015-cover.jpg');
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (2,'Terminator','Terminator movie','https://www.youtube.com/embed/jNU_jrPxs-0?autoplay=0',1,'http://www.coverwhiz.com/content/Terminator-2-Judgement-Day.jpg');
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (21,'BLACK MASS','Black Mass movie','https://www.youtube.com/embed/4XD0Q8JW9qw?autoplay=0',1,'http://ia.media-imdb.com/images/M/MV5BNzg0ODI3NDQxNF5BMl5BanBnXkFtZTgwMzgzNDA0NjE@._V1_SX214_AL_.jpg');
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (22,'LEGEND','Legend movie','https://www.youtube.com/embed/yI3v6KfR9Mw?autoplay=0',1,'http://images.fandango.com/r98.2/ImageRenderer/164/250/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/184191/legend_tsr1sheet5_rgb.jpg');
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (23,'THE WALK','The walk movie','https://www.youtube.com/embed/4W6byFcD5uE?autoplay=0',1,'http://images.fandango.com/r98.2/ImageRenderer/164/250/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/179060/walk_imax_payoff_poster_lo.jpg');
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (24,'MAZZ RUNNER','Mazz Runner movie','https://www.youtube.com/embed/-44_igsZtgU?autoplay=0',1,'http://images.fandango.com/r98.2/ImageRenderer/164/250/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/180877/scorchtrialsposter.jpg');
Insert into TESTDB.M_MOVIES (ID,TITLE,DESCRIPTION,TRAILERS,AVAILABILITY,COVER_PICTURE) values (25,'HOTEL TRANSYLVANIA 2','Hotel Transylvania 2 movie','https://www.youtube.com/embed/i73c3dgGxRQ?autoplay=0',1,'http://images.fandango.com/r98.2/ImageRenderer/164/250/redesign/static/img/default_poster.png/0/images/masterrepository/fandango/161125/hoteltrans2poster.jpg');
REM INSERTING into TESTDB.M_REVIEWS
SET DEFINE OFF;
Insert into TESTDB.M_REVIEWS (ID,MOVIE_ID,ADMIN_ID,RATINGSCALE,REVIEW,R_DATE) values (22,1,1,4,'I liked it','24062928');
Insert into TESTDB.M_REVIEWS (ID,MOVIE_ID,ADMIN_ID,RATINGSCALE,REVIEW,R_DATE) values (1,1,1,5,'Nice!','24062835');
Insert into TESTDB.M_REVIEWS (ID,MOVIE_ID,ADMIN_ID,RATINGSCALE,REVIEW,R_DATE) values (21,1,1,3,'Amazing','24062926');
REM INSERTING into TESTDB.M_SHOWTIME
SET DEFINE OFF;
Insert into TESTDB.M_SHOWTIME (ID,MOVIE_ID,M_DATE,TIME_FROM,TIME_TO,HALL_ID,STATUS) values (4,1,'2000000000000000','2000000000000000','2000000000000000',1,'On time');
REM INSERTING into TESTDB.M_THEATRE
SET DEFINE OFF;
Insert into TESTDB.M_THEATRE (ID,NAME,ADDRESS,CITY,STATE,ZIPCODE,PHONENUMBER) values (1,'AMC Arapahoe','100 S arapahoe st','Aurora','CO','80111','(720) 620 1389');
REM INSERTING into TESTDB.M_TICKETS
SET DEFINE OFF;
Insert into TESTDB.M_TICKETS (ID,MOVIE_ID,PRICE,DATE_FROM,DATE_TO) values (1,1,10,'1000000000000','1100000000000');
REM INSERTING into TESTDB.M_USERTICKETS
SET DEFINE OFF;
Insert into TESTDB.M_USERTICKETS (ID,ADMINE_ID,SHOWTIME_ID,TICKET_ID,RESERVE_DATE) values (1,1,4,1,'2000000000000');
--------------------------------------------------------
--  DDL for Index M_ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_ADMIN_PK" ON "TESTDB"."M_ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_CART_PK" ON "TESTDB"."M_CART" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."TABLE1_PK" ON "TESTDB"."M_HALL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_MOVIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_MOVIES_PK" ON "TESTDB"."M_MOVIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_REVIEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_REVIEWS_PK" ON "TESTDB"."M_REVIEWS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_SHOWTIME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_SHOWTIME_PK" ON "TESTDB"."M_SHOWTIME" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_THEATRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_THEATRE_PK" ON "TESTDB"."M_THEATRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_TICKETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_TICKETS_PK" ON "TESTDB"."M_TICKETS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index M_USERTICKETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."M_USERTICKETS_PK" ON "TESTDB"."M_USERTICKETS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table M_ADMIN
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_ADMIN" ADD CONSTRAINT "M_ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_ADMIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_CART
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_CART" ADD CONSTRAINT "M_CART_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_CART" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_HALL
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_HALL" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_HALL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_MOVIES
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_MOVIES" ADD CONSTRAINT "M_MOVIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_MOVIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_REVIEWS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_REVIEWS" ADD CONSTRAINT "M_REVIEWS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_REVIEWS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_SHOWTIME
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_SHOWTIME" ADD CONSTRAINT "M_SHOWTIME_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_SHOWTIME" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_THEATRE
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_THEATRE" ADD CONSTRAINT "M_THEATRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_THEATRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_TICKETS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_TICKETS" ADD CONSTRAINT "M_TICKETS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_TICKETS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table M_USERTICKETS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_USERTICKETS" ADD CONSTRAINT "M_USERTICKETS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."M_USERTICKETS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table M_CART
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_CART" ADD CONSTRAINT "ADMINES_ID" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "TESTDB"."M_ADMIN" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."M_CART" ADD CONSTRAINT "SHOWTIMES_ID" FOREIGN KEY ("SHOWTIME_ID")
	  REFERENCES "TESTDB"."M_SHOWTIME" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."M_CART" ADD CONSTRAINT "TICKET_ID" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "TESTDB"."M_TICKETS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table M_HALL
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_HALL" ADD CONSTRAINT "THEATRE_ID" FOREIGN KEY ("THEATRE_ID")
	  REFERENCES "TESTDB"."M_THEATRE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table M_REVIEWS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_REVIEWS" ADD CONSTRAINT "ADMIN_ID" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "TESTDB"."M_ADMIN" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."M_REVIEWS" ADD CONSTRAINT "MOVIE_ID" FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "TESTDB"."M_MOVIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table M_SHOWTIME
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_SHOWTIME" ADD CONSTRAINT "HALLID" FOREIGN KEY ("HALL_ID")
	  REFERENCES "TESTDB"."M_HALL" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."M_SHOWTIME" ADD CONSTRAINT "MOVIEID" FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "TESTDB"."M_MOVIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table M_TICKETS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_TICKETS" ADD CONSTRAINT "MOVIES_ID" FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "TESTDB"."M_MOVIES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table M_USERTICKETS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."M_USERTICKETS" ADD CONSTRAINT "ADMINESS_ID" FOREIGN KEY ("ADMINE_ID")
	  REFERENCES "TESTDB"."M_ADMIN" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."M_USERTICKETS" ADD CONSTRAINT "SHOW_TIME_ID" FOREIGN KEY ("SHOWTIME_ID")
	  REFERENCES "TESTDB"."M_SHOWTIME" ("ID") ENABLE;
  ALTER TABLE "TESTDB"."M_USERTICKETS" ADD CONSTRAINT "TICKETS_ID" FOREIGN KEY ("TICKET_ID")
	  REFERENCES "TESTDB"."M_TICKETS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_ADMIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_ADMIN_TRG" 
BEFORE INSERT ON M_ADMIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_ADMIN_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_ADMIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_CART_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_CART_TRG" 
BEFORE INSERT ON M_CART 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_CART_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
    IF INSERTING THEN
      SELECT M_CART_SEQ.NEXTVAL INTO :NEW.TOTAL_PRICE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_CART_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_HALL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_HALL_TRG" 
BEFORE INSERT ON M_HALL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT M_HALL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_HALL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_MOVIES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_MOVIES_TRG" 
BEFORE INSERT ON M_MOVIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_MOVIES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_MOVIES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_REVIEWS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_REVIEWS_TRG" 
BEFORE INSERT ON M_REVIEWS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_REVIEWS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_REVIEWS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_SHOWTIME_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_SHOWTIME_TRG" 
BEFORE INSERT ON M_SHOWTIME 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_SHOWTIME_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_SHOWTIME_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_THEATRE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_THEATRE_TRG" 
BEFORE INSERT ON M_THEATRE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_THEATRE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_THEATRE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_TICKETS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_TICKETS_TRG" 
BEFORE INSERT ON M_TICKETS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_TICKETS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_TICKETS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger M_USERTICKETS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TESTDB"."M_USERTICKETS_TRG" 
BEFORE INSERT ON M_USERTICKETS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT M_USERTICKETS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TESTDB"."M_USERTICKETS_TRG" ENABLE;
